version: '3'

volumes:
  pg-data:
  app:

services:
  db:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - PORT=${PORT}
    ports:
      - "4000:4000"
    container_name: nest-app
    volumes:
      - .:/app
    depends_on:
      - db
